### ISSUE TITLE
Typescript: Wrong type used in router/index.ts

### ISSUE THREAD

**Issue by Mik13** [quasarframework/quasar-starter-kit#109]
Hi everybody! First of all, thanks for the awesome work!

I have found a problem with the starter kit here:
https://github.com/quasarframework/quasar-starter-kit/blob/04ffe2319dca0556467082929f73f719674b018f/template/src/router/index.ts#L11

`StoreInterface` is used as type to the call of the route wrapper.
But the `store` param is not of type `StoreInterface` but of `Store<StoreInterface>` with Store coming from vuex. Without changing `{{#preset.vuex}}<StoreInterface>{{/preset.vuex}}` to `{{#preset.vuex}}<Store<StoreInterface>>{{/preset.vuex}}` (and importing Store from vuex) using the store parameter causes errors.

Keep up the good work! Best regards!

**Comment by webnoob** [comment]
Resolved with latest merge.
