### ISSUE TITLE
Including module-example in store prevents SSR from rendering

### ISSUE THREAD

**Issue by JCharante** [quasarframework/quasar-starter-kit#118]
**Describe the bug**

Trying to include module-example in your newly created typescript  project will prevent SSR from working properly.

This issue does not occur when creating a new store with the CLI, as the CLI does not create new stores with a module format (it'll export default a dict, it doesn't create a Module that it then exports).

**To Reproduce**
1. $ quasar create example # Enable Vuex, Typescript and Class based composition during this
2. Go to [store/index.ts](https://github.com/quasarframework/quasar/blob/dev/app/templates/store/ts/index.ts) and uncomment lines 4, 5, and 24. This is to include the module-example in your store.
3. $ quasar dev -m ssr
4. Load the page on your web browser, you will encounter:

![image](https://user-images.githubusercontent.com/13973198/84745957-80b2f100-afdf-11ea-8f24-4119596af67d.png)

And in the console

![image](https://user-images.githubusercontent.com/13973198/84746084-a8a25480-afdf-11ea-8fc2-d5007480c191.png)

**Expected behavior**
The page should load normally. It does load normally if you run `$ quasar dev -m spa`

**Platform (please complete the following information):**
OS: Windows 10
Node: v12.17.0
NPM: 6.14.4

**Additional context**
I have identified the fix for this and talked to @IlCallo in `@discord/V1 Help/#ssr` about this. I'm creating the issue so I can create the PR to rename `module` in `module-example/index.ts` to `exampleModule`.

**Comment by rstoenescu** [comment]
Thanks for also fixing this!
