### ISSUE TITLE
EssentialLink does not use openURL

### ISSUE THREAD

**Issue by tomers** [quasarframework/quasar-starter-kit#134]
EssentialLink should use [Quasar's standard way to open external URL](https://quasar.dev/quasar-utils/other-utils#Open-External-URL).

Instead, it hard-codes `tag="a"`, `target="_blank"` and `:href="link"`, which is too low-level and is not the best known method to open external links in the framework.

Reference: https://github.com/quasarframework/quasar-starter-kit/blob/master/template/src/components/EssentialLink.vue#L4

```
  <q-item
    clickable
    tag="a"
    target="_blank"
    :href="link"
  >
```

**Comment by rstoenescu** [comment]
Hi,

There is no "best method". Both are equally valuable. The so called "low-level" one is best for SSR as it renders the actual link so crawlers can access it. The openURL is best for Cordova/Capacitor/... as it taps into the native API. It all depends on what your needs are.
