### ISSUE TITLE
Relative module not found on i18n - branch next

### ISSUE THREAD

**Issue by ovidiuc** [quasarframework/quasar-starter-kit#139]
**Describe the bug**
After you generate a new project, with i18n included, and run `quasar dev`, it doesn't compile,
because the relative import on i18n has the wrong casing:

https://github.com/quasarframework/quasar-starter-kit/blob/b2021500714486aa1b3e4990f845a533ae40d3d8/template/src/i18n/index.js#L1

https://github.com/quasarframework/quasar-starter-kit/blob/b2021500714486aa1b3e4990f845a533ae40d3d8/template/src/i18n/index.ts#L1

```
import enUS from './en-US'
```

but the directory is `en-us`.

**To Reproduce**
Create an new project:
`quasar create quasar.i18n-issue-n5 --branch next`

```
? Project name (internal usage for dev) quasar.i18n-issue-n5
? Project product name (must start with letter if building mobile apps) Quasar App
? Project description A Quasar Framework app
? Author
? Pick your CSS preprocessor: SCSS
? Check the features needed for your project: Vue-i18n
? Continue to install project dependencies after the project has been created? (recommended) yarn
``` 
Run `quasar dev`.

You get this error:
```

Failed to compile with 1 errors

This relative module was not found:

* ./en-US in ./src/i18n/index.js
```

**Expected behavior**
The generated project template should compile.

**Platform (please complete the following information):**
OS:  Debian GNU/Linux 9 (Docker)
Node: v14.15.1
NPM:
Yarn: 1.22.5
Browsers:
iOS:
Android:
Electron:

 Pkg quasar........ v2.0.0-beta.5
 Pkg @quasar/app... v3.0.0-beta.7

**Additional context**

**Comment by rstoenescu** [comment]
Thanks for providing a PR!
