### ISSUE TITLE
SSR mode use axios cross-request state pollution

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar-starter-kit#154]
Using axios according to the template generated by the current cli has the problem of cross-request state pollution, and the ssr part of the document does not correctly explain it.

You can refer to this article to modify.

https://dev.to/quasar/quasar-ssr-using-cookies-with-other-libs-services-4nkl

But this article is based on the old version of v1, the way I use it in the v2 version is：

```
import { boot } from "quasar/wrappers";
import axios, { AxiosInstance } from "axios";

declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $axios: AxiosInstance;
  }
}
declare module "vuex/types/index" {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface Store<S> {
    $axios: AxiosInstance;
  }
}

declare module "vue-router/dist/vue-router" {
  interface Router {
    $axios: AxiosInstance;
  }
}

export default boot(({ app, store, router, ssrContext }) => {
  // 避免交叉请求状态污染 (cross-request state pollution)
  const $axios = axios.create();
  app.config.globalProperties.$axios = $axios;
  store.$axios = $axios;
  router.$axios = $axios;
});
```

**Comment by rstoenescu** [comment]
Added instructions into the starter kit.

I've especially written [a section on docs](https://next.quasar.dev/quasar-cli/developing-ssr/writing-universal-code#avoid-stateful-singletons) on the Stateful Singleton pattern when on SSR and its pitfalls, but adding a warning + instructions on the starter kit doesn't hurts. So thank you for this ticket.

**Comment by kuntik17** [comment]
I followed the instructions on the docs but I get

"was not found in 'vue-router' (possible exports: BaseTransition, Comment, EffectScope, Fragment, KeepAlive, ReactiveEffect, Static, Suspense, Teleport, Text, Transition, TransitionGroup, VueElement, callWithAsyncErrorHandling, callWithErrorHandling, camelize, capitalize, cloneVNode, compatUtils, compile, computed, createApp, createBlock, createCommentVNode, createElementBlock, createElementVNode, createHydrationRenderer, createPropsRestProxy, createRenderer, createSSRApp, createSlots, createStaticVNode, createTextVNode, createVNode, customRef, defineAsyncComponent, defineComponent, defineCustomElement, defineEmits, defineExpose, defineProps, defineSSRCustomElement, devtools, effect, effectScope, getCurrentInstance, getCurrentScope, getTransitionRawChildren, guardReactiveProps, h, handleError, hydrate, initCustomFormatter, initDirectivesForSSR, inject, isMemoSame, isProxy, isReactive, isReadonly, isRef, isRuntimeOnly, isVNode, markRaw, mergeDefaults, mergeProps, nextTick, normalizeClass, normalizeProps, normalizeStyle, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, openBlock, popScopeId, provide, proxyRefs, pushScopeId, queuePostFlushCb, reactive, readonly, ref, registerRuntimeCompiler, render, renderList, renderSlot, resolveComponent, resolveDirective, resolveDynamicComponent, resolveFilter, resolveTransitionHooks, setBlockTracking, setDevtoolsHook, setTransitionHooks, shallowReactive, shallowReadonly, shallowRef, ssrContextKey, ssrUtils, stop, toDisplayString, toHandlerKey, toHandlers, toRaw, toRef, toRefs, transformVNodeArgs, triggerRef, unref, useAttrs, useCssModule, useCssVars, useSSRContext, useSlots, useTransitionState, vModelCheckbox, vModelDynamic, vModelRadio, vModelSelect, vModelText, vShow, version, warn, watch, watchEffect, watchPostEffect, watchSyncEffect, withAsyncContext, withCtx, withDefaults, withDirectives, withKeys, withMemo, withModifiers, withScopeId)"

error..

**Comment by IlCallo** [comment]
@kuntik17 are you on latest quasar version?

**Comment by kuntik17** [comment]
Yes.

**Comment by panhezeng** [comment]
> Yes.
> 
> // src/router/index.js export default function (/* { store, ssrContext } */) { const Router = new VueRouter({...}) return Router }

SSR can't write

use 

```
import { route } from "quasar/wrappers";

export default route<any>(function ({ store, ssrContext }) {
  const createHistory = process.env.SERVER
    ? createMemoryHistory
    : process.env.VUE_ROUTER_MODE === "history"
    ? createWebHistory
    : createWebHashHistory;

...

}


```
