### ISSUE TITLE
Vue Class Component - Project Inactivity and HMR Failure

### ISSUE THREAD

**Issue by MatthewSH** [quasarframework/quasar-starter-kit#164]
I don't think the option should be removed, however I think a warning or something should be added beside the prompt https://github.com/quasarframework/quasar-starter-kit/blob/7cf4e7da17fc715011501b749444dfa5fcc105d7/meta.js#L96

Even if it just looks like:
```
Class-based (https://github.com/vuejs/vue-class-component & https://github.com/kaorun343/vue-property-decorator) NOTE: HMR does not function correctly with class-based projects.
```

Or maybe just a new prompt as a whole to acknowledge the potential issue. It seems this bug has existed for months (reported initially in February on Quasar, then issues open on vue-class-component in late March) without acknowledgement from the devs.

For reference:
https://github.com/vuejs/vue-class-component/issues/521
https://github.com/quasarframework/quasar/issues/10527
https://github.com/quasarframework/quasar/issues/8534

**Comment by IlCallo** [comment]
We're considering this, in case we cannot find a solution by ourselves or with Vue team support

**Comment by thekingrenz23** [comment]
i like the class based approach hopefully it be fixed

**Comment by IlCallo** [comment]
Razvan was finally able to pin-point the problem into a vue loader bug: https://github.com/vuejs/vue-loader/pull/1897
We're still going to mark Class API as deprecated, but at least the HMR problem will be fixed in next vue-loader version

**Comment by rstoenescu** [comment]
Seems that my PR has been merged and the vue-loader team has released a new version.
So upgraded to the new vue-loader in "@quasar/app" v3.1.9 -- highly recommended for those using the Class API.

Enjoy!
