### ISSUE TITLE
readme has incorrect quasar create

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar-starter-kit#165]
**Describe the bug**
Given that this is a started kit I believe that the readme should show the command as ```quasar create -kit quasarframework/quasar-starter-kit``` as this is how a kit should be used. If this is the kit used by default when ```quasar create``` runs then this should be noted and explained that -kit can be omitted.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment]
We’ve been really careful to not introduce confusion in docs. The quasar create command uses this starter kit (which is the only official one) and it’s implicit. Should the user want to create his own (or use a community starter kit) then that’s what the “—kit” param is designed for.

In which readme did you find incorrect information?

**Comment by julie777** [comment]
The one for quasar-starter-kit. It doesn't specify --kit in the command show because it doesn't need to. However, nowhere in the readme can I find that using this starter kit is the default for creating Quasar projects.

**Comment by rstoenescu** [comment]
But it clearly states that “quasar create” will create a Quasar project.. and by reading this in the readme of this repo it is implicit…
