### ISSUE TITLE
Failed to Download Starter Kit when Creating Quasar Project

### ISSUE THREAD

**Issue by CynthiaBlue** [quasarframework/quasar-starter-kit#168]
I have installed Quasar on a new MacBook and when I try to create a new quasar project I get the following error:
``` Quasar CLI · Failed to download repo quasarframework/quasar-starter-kit#master: EPERM: operation not permitted, utime '/Users/mymac/.quasar-starter-kits/quasarframework-quasar-starter-kit#master/.github'```

Searching Google doesn't come up with much, but one result was that possibly the starter kit download is not currently available.  Could this be the case?
 
 This is my Quasar Info:

<img width="421" alt="Screen Shot 2021-11-02 at 7 02 30 PM" src="https://user-images.githubusercontent.com/34698014/139975866-28047927-ad2d-404c-8bef-e89702dc189e.png">

**Comment by IlCallo** [comment]
Just tried with your same Node and NPM versions, doesn't seem there's any problem
Could you try again? It may have been a temporarly problem with GitHub

**Comment by rstoenescu** [comment]
Cross-ref: https://github.com/quasarframework/quasar/discussions/11193
