### ISSUE TITLE
Browserlist is too inclusive

### ISSUE THREAD

**Issue by SKFrozenCloud** [quasarframework/quasar-starter-kit#176]
**Describe the bug**
The browserlist includes Safari 13 that adds 42 kB of polyfill with core-js.
Remove unrelevant polyfill.

**To Reproduce**
Browserlist currently includes support for Safari 13 and Safari 13 for IOS.
Safari 13 and versions below is used by ~2.53% as seen on https://caniuse.com/webp.

**Expected behavior**
See below

**Screenshots**
Current browserlist:
![image](https://user-images.githubusercontent.com/39242670/155688583-ea8ff21c-3a25-4921-9d5a-318174935606.png)

"last 10 Chrome versions",
"last 10 Firefox versions",
"last 4 Edge versions",
"last 5 Opera versions",
"last 8 Android versions",
"last 8 ChromeAndroid versions",
"last 8 FirefoxAndroid versions",
"last 7 Safari versions",
"last 10 iOS versions"

Browserlist **without** Safari 13:
![image](https://user-images.githubusercontent.com/39242670/155688493-5ae79fe7-d629-4b7b-9b3f-5b19387a91c6.png)

"last 10 Chrome versions",
"last 10 Firefox versions",
"last 4 Edge versions",
"last 7 Safari versions, not safari < 14",
"last 8 Android versions",
"last 8 ChromeAndroid versions",
"last 8 FirefoxAndroid versions",
"last 10 iOS versions, not ios_saf < 14",
"last 5 Opera versions"

**Platform (please complete the following information):**
OS: Linux
Node: 16
NPM: 8
Yarn: 1.22
Browsers: Firefox
iOS:
Android:
Electron:

**Additional context**

**Comment by IlCallo** [comment]
IIRC we defined this list taking it from some kind of standard to get higher support percentage as possible.
You're of course free to change your projects to avoid supporting some browsers you don't like, but the decision to drop a browser should be in the hands of the dev, not on our defaults.

I'll still add a bullet point into Qv3 changes to check out browser usage when releasing the new major version and possibly drop some older browser versions

**Comment by SKFrozenCloud** [comment]
Safari 13 was the only browser I found when testing browserlists that requires a lot of polyfill. The rest was fine.

Of course the default should be as inclusive as possible but you also don't want to keep support browsers that require unnecessary polyfill just because users still use it. Just like IE11.

**Comment by IlCallo** [comment]
IE11 support has been dropped by an upstream dep (Vue3) because there were some un-polyfillable features, so it's not really the same situation
But I agree on changing the defaults to exclude Safari older versions in next major version, thanks for reporting your tests results
