### ISSUE TITLE
i18n plugin imports store but doesn't use it

### ISSUE THREAD

**Issue by omrihar** [quasarframework/quasar-starter-kit#29]
### Software version

Quasar: 0.15.1
OS: Manjaro Linux
Node: 9.5.0

### What did you get as the error?
Linter throws a no unusded vars erro

### What were you expecting?
No errors from the linter in the starter kit

### What steps did you take, to get the error?
Simply run the starter kit with
`quasar init <project>`
enable linter and select AirBnb style.
Then start `quasar dev`.
It will not start and give a 'no-unused-vars' error. It's quite simple to solve since the i18n plugin imports the store but never uses it. Either add something like `locale: store.state.locale` or don't import the store.

I guess for the educational purposes it's good to have the store imported and since the locale variable is not defined in the store yet, it's good not to use it, but this way you get immediately an error.

**Comment by rstoenescu** [comment]
Hi,

Fixed it. Thanks for reporting.

**Comment by rstoenescu** [comment]
Fixed it. Thanks for reporting.
