### ISSUE TITLE
Auto sitemap generation

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit#34]
I'm still learning about optimizing my Quasar websites for search engines.
One of the things Google suggests at their [search console](https://www.google.com/webmasters/tools/settings) is to upload a sitemap.

It would be great if Quasar could provide the sitemap generation from the box.

Other sources that could be taken into consideration:
https://github.com/chrisvfritz/prerender-spa-plugin
But these are very high level and not easy to understand.

**Comment by rstoenescu** [comment]
This is out of Quasar's control. Your vue router config (on routes) determines your sitemap. Should Quasar handle the routes automatically for you, like Nuxt (through convention over configuration), then it would have been possible to do it. Otherwise it's not possible.

**Comment by mesqueeb** [comment]
Ok I understand! Do you have any hints on how to make Quasar apps more SEO friendly?
