### ISSUE TITLE
[PWA] Workbox support

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar-starter-kit#36]
From [Google](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw):
> Developers who have previously used sw-precache and/or sw-toolbox have a straightforward upgrade path to the Workbox family of libraries. Upgrading to Workbox will provide a modern, extensible service worker experience with improved debugging and developer ergonomics.

Migration guide: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw#from_the_sw-precache-webpack-plugin_to_the_workbox_webpack_plugin

Vue CLI 3 PWA plugin supports workbox: https://github.com/vuejs/vue-cli/issues/717

**Comment by rstoenescu** [comment]
This should go into quasar-cli repo. Available in future CLI v0.16.0

**Comment by rstoenescu** [comment]
No, it just means Quasar CLI will use Workbox.
