### ISSUE TITLE
Confusing text in comment in router/index.js

### ISSUE THREAD

**Issue by omrihar** [quasarframework/quasar-starter-kit#37]
I found the comment in `src/router/index.js` instructing to set the Vue Router mode in quasar.conf.js a bit confusing because 'history' mode is set by default in the starter kit. When reading the comment it sounds like the default is something else, because it asks the user to also change a different setting (`build.publicPath`) if "history" mode is chosen.

This is a small thing, but upgrading from q0.14 I didn't notice at first that the default mode was "history" mode and took me a while to catch that.

Thanks for the great work!
Omri

**Comment by rstoenescu** [comment]
Changed it. Thanks for this!

**Comment by omrihar** [comment]
You're welcome :)
