### ISSUE TITLE
vendor.*.js throws TypeError: *.e is not a function (blank page, crashed)

### ISSUE THREAD

**Issue by km333** [quasarframework/quasar-starter-kit#44]
### Software version
Operating System        	Linux(4.13.0-45-generic) - linux/x64
NodeJs                  	8.11.2
Global packages         	
  NPM                   	6.1.0
  yarn                  	1.7.0
  quasar-cli            	0.16.4
  vue-cli               	2.9.6
  cordova               	Not installed
Important local packages	
  quasar-cli            	0.16.4	(Quasar Framework CLI)
  quasar-framework      	0.16.0	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras         	2.0.2	(Quasar Framework fonts, icons and i18n.)
  vue                   	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router            	3.0.1	(Official router for Vue.js 2)
  vuex                  	3.0.1	(state management for Vue.js)
  electron              	Not installed
  electron-packager     	Not installed
  electron-builder      	Not installed
  @babel/core           	7.0.0-beta.49	(Babel compiler core.)
  webpack               	4.9.1	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server    	3.1.4	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin	3.2.0	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
OS: Ubuntu 17.10
Browsers: Chromium 66/Firefox 60
Any other software related to your bug: http-server@0.11.1

### What did you get as the error?

blank page/js crashed

Stack trace:
vendor.ded481d8.js:14 TypeError: i.e is not a function
    at component (vendor.ded481d8.js:14)
    at vendor.ded481d8.js:14
    at vendor.ded481d8.js:14
    at Array.map (<anonymous>)
    at vendor.ded481d8.js:14
    at Array.map (<anonymous>)
    at Vt (vendor.ded481d8.js:14)
    at vendor.ded481d8.js:14
    at h (vendor.ded481d8.js:14)
    at n (vendor.ded481d8.js:14)

### What were you expecting?

page to load OK without errors

### What steps did you take, to get the error?

1. quasar init myproject (makes no difference which options are selected)
2. cd myproject && npm install
2. quasar build -m spa (same outcome with -m pwa)
3. http-server dist/spa-mat/

### Further notes: 
1. It works fine in dev mode this is only an issue with build
2. In the vendor file it's ocurring in the line under the comment
/*!
 * Determine if an object is a Buffer
 *
 * @author   Feross Aboukhadijeh <https://feross.org>
 * @license  MIT
 */
3.  Here's other things I tried (none fixed it):
a.. Rolled back quasar-cli to 0.16.1, fresh init/build
b. Rolled back vue-init to 2.9.6, fresh init/build
c. Rolled back quasar-cli to 0.15.4, fresh init/build

However my previous (working fine) quasar project was built using v0.15.4 (only about 2-3 months ago)
So I am quite sure a recent change in the starter-kit template is causing this.
I can see there have been a few in this window mainly around babel config/versions and other version changes.

4. Other users have noticed this issue (https://github.com/quasarframework/quasar/issues/2103)

Any help appreciated.

Rgds
Mike

**Comment by rstoenescu** [comment]
Hi,

Root cause: Webpack 4 (possibly Webpack 3 too) does not allow to lazy load a parent layout/page then not lazy loading any children. What I mean is:

```js
import Two from './two.vue'

//...then routes:

{
  path: '/something',
  // lazy load a layout/page with children
  component: () => import('./something.vue'),

  children: [
    // lazy load -> GOOD
    {path: 'one', component: () => import('./one.vue')},

    // not lazy load -> BAD! we got the parent lazy loading,
    // so we are forced to lazy load this too
    {path: 'two', component: Two}
  ]
}
```

**Comment by skmbr** [comment]
Not sure I understand..... My routes.js looks like this:

```
export default [
  {
    path: '/',
    component: () => import('components/Main'),
    children: [
      {
        path: '',
        meta: {
          title: 'Tenpin Toolkit',
          toolName: 'splash'
        },
        component: () => import('components/Splash')
      },
      {
        path: 'axis',
        meta: {
          title: 'Axis Tilt & Rotation',
          toolName: 'axis'
        },
        component: () => import('components/Axis')
      },
      {
        path: 'speed',
        meta: {
          title: 'Ball Speed & RPM',
          toolName: 'speed'
        },
        component: () => import('components/Speed')
      },
     [ OTHER ROUTES REMOVED - all defined the same way ]
  ]
  },

  { // Always leave this as last one
    path: '*',
    component: () => import('pages/404')
  }
]
```

If I'm reading your post right, mine are all done in the "GOOD" way?

The bizarre thing for me with this issue is that setting everything up on another computer works fine, but I'm going to have to give that back soon at which point I'm going to be stuck not able to build my apps any more. :(

**Comment by rstoenescu** [comment]
Gonna reopen this, but it's a Webpack issue... the error comes from Webpack. Currently don't have time to fully investigate as I'm preparing the SSR release :((

**Comment by km333** [comment]
@rstoenescu, 
My routes.js (and every other file) is exactly as in the template (unchanged)
https://github.com/quasarframework/quasar-starter-kit/blob/master/template/src/router/routes.js
Totally fresh install with no changes.

@skmbr,
 if you really need to get it building you could go back to non-lazy routes for the meantime.
ie

import Default from '../layouts/default'
import Index from '../pages/index'
import PageNotFound from '../pages/404'

export default [
  {
    path: '/',
    // component: () => import('layouts/default'),
    component: Default,
    children: [
      // { path: '',component: () => import('pages/index') }
      { path: '', component: Index }
    ]
  },
  {
    // Always leave this as last one
    path: '*',
    component: PageNotFound
    // component: () => import('pages/404')
  }
]

**Comment by skmbr** [comment]
@km333 Thanks for the tip! May have to do that. 

What are the performance implications of using non-lazy routes?

**Comment by rstoenescu** [comment]
Every route's code is loaded at startup.

**Comment by robshep** [comment]
Confirm this workaround works for me given the same symptom in 0.16.0

**Comment by matheusb-comp** [comment]
I don't know exactly what causes this problem, but the `routes.js` file in the development server makes the imports like this:
```
{
  path: '/',
  component: function component() {
    return __webpack_require__.e(/*! import() */ 0).then(__webpack_require__.bind(null, /*! layouts/default */ "./src/layouts/default.vue"));
  },
```
And after `quasar build`, the final code is like this:
```
[{
    path: "/",
    component: function() {
        return n.e(0).then(n.bind(null, "ez0Y"))
    },
```
The issue [#4842](https://github.com/webpack/webpack/issues/4842) on Webpack's repository apparently is about this, and was [solved](https://github.com/webpack/webpack/issues/4842#issuecomment-305345157) by using Airbnb's [Babel plugin](https://github.com/airbnb/babel-plugin-dynamic-import-node) for dynamic import.
After addding `["dynamic-import-node"]` to the `.babelrc` file, the final code works, and looks like this:
```
[{
    path: "/",
    component: function() {
        return Promise.resolve().then(function() {
            return Ce()(n("ez0Y"))
        })
    },
```

**Comment by pvkovalev** [comment]
If anyone experiences this issue

> TypeError: undefined is not an object (evaluating 'e[0].match') 

Well, solutions is the same [(babel-plugin-dynamic-import-node):](https://github.com/airbnb/babel-plugin-dynamic-import-node)
`npm install babel-plugin-dynamic-import-node --save-dev`
and add this into `.babelrc` file

```
{
  "plugins": ["dynamic-import-node"]
}
```

**Comment by IlCallo** [comment]
Is this still a problem? Seems `babel-plugin-dynamic-import-node` and `babel-plugin-module-resolver` deps are still needed into `@quasar/babel-preset-app` package.json, but never used

**Comment by IlCallo** [comment]
Closing as stale
