### ISSUE TITLE
prop "letter" QItemSide

### ISSUE THREAD

**Issue by llulioscesar** [quasarframework/quasar-starter-kit#50]
## Global packages
  NPM                           6.4.1
  yarn                          Not installed
  quasar-cli                    0.17.19
  vue-cli                       2.9.6
  cordova                       8.0.0

## Important local packages
  1. quasar-cli                    0.17.19 (Quasar Framework CLI)
  2. quasar-framework              0.17.16 (Build responsive SPA, SSR, PWA, Hybrid ## Mobile Apps and Electron apps, all simultaneously using the same codebase)
  3. quasar-extras                 2.0.6   (Quasar Framework fonts, icons and animations)
  4. vue                           2.5.17  (Reactive, component-oriented view layer for modern web interfaces.)
  5. vue-router                    3.0.1   (Official router for Vue.js 2)
  6. vuex                          3.0.1   (state management for Vue.js)
  7. electron                      3.0.0   (Build cross platform desktop apps with JavaScript, HTML, and CSS)
  8. electron-packager             12.1.2  (Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI)
  9. electron-builder              20.28.4 (A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box)
  10. @babel/core                   7.0.0-beta.54   (Babel compiler core.)
  11. webpack                       4.19.1  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  12. webpack-dev-server            3.1.8   (Serves a webpack app. Updates the browser on changes.)
  13. workbox-webpack-plugin        3.5.0   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  14. register-service-worker       1.5.2   (Script for registering service worker, with hooks)

### What did you get as the error?
Invalid prop: custom validator check failed for prop "letter".
I try to show a dynamic number from an array in QItemSide

### What were you expecting?
I did not expect any error

### What steps did you take, to get the error?
console electron

**Comment by rstoenescu** [comment]
Hi,

Please log any bugs to Quasar's main repo. This has nothing to do with the CLI's starter kit.
To answer your problem: the "letter" prop expects a String of length strictly equal to 1. Examples: `'1'`, `'a'`, `'A'`.
