### ISSUE TITLE
Eslint plugin Vue 5 released

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar-starter-kit#55]
Today has been released the new stable version on eslint plug-in for Vue:
https://github.com/vuejs/eslint-plugin-vue
Could someone to update and test it?
Cheers,
Francesco

**Comment by rstoenescu** [comment]
Hi,

Done for future v1.0 -- will try to find some time to port to 0.17 too.

Note that you can manually update to it in your current project since ESLint stuff is not connected to the CLI in any way.
