### ISSUE TITLE
Enable strict mode for vuex in development

### ISSUE THREAD

**Issue by bezany** [quasarframework/quasar-starter-kit#58]
I suggestion enable `strict` mode for `vuex` in 'development'.
Inset code
```javascript
strict: process.env.NODE_ENV === 'development'
```
[here](https://github.com/quasarframework/quasar-starter-kit/blob/master/template/src/store/index.js#L14)
Not sure the check `process.env.NODE_ENV` is best solution.

**Comment by rstoenescu** [comment]
Added. Thanks!
