### ISSUE TITLE
Failed to restore plugin "cordova-plugin-whitelist" from config.xml

### ISSUE THREAD

**Issue by evazc** [quasarframework/quasar-starter-kit#75]
**Describe the bug**
it appears when I run `quasar build -m cordova -T android` without folders 'node_modules, platforms, plugins' under `/src-cordova`(which are ignored by git)

**To Reproduce**
1. create a quasar-cli project with android platform
2. delete 'node_modules, platforms, plugins' folders under `/src-cordova`
3. run `quasar build -m cordova -T android`

**Screenshots**
![image](https://user-images.githubusercontent.com/26076008/69714102-c5a93000-1140-11ea-98a2-194354ae477e.png)

**Platform (please complete the following information):**
OS: both Windows and macOS
Node: 12.13.1
NPM: 6.12.1
Yarn: 1.10.1
Cordova: 9.0.0
@quasar/cli: 1.0.2

**Comment by ankcode** [comment]
Hi @evazc I see you closed this, did you find a solution for it, I am also getting a similar error.

**Comment by evazc** [comment]
Hi @ankcode 

This is a cordova-cli issue.

Run npm i in the 'src-cordova' folder before you run build command.

**Comment by rstoenescu** [comment]
Maybe I can enhance Quasar CLI to npm install it for you guys so we can eliminate this cordova-cli issue. Will look into it as time allows.
